apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-ex
  labels:
    app: nodejs-ex
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodejs=quay.io/kanaet3888/nodejs
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-ex
  template:
    metadata:
      labels:
        app: nodejs-ex
    spec:
      containers:
        - name: nodejs
          image: quay.io/kanaet3888/nodejs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080